# Generated by Django 5.0.7 on 2024-08-17 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fooditem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itempic", models.ImageField(upload_to="images")),
                ("itemname", models.CharField(max_length=100)),
                ("price", models.FloatField()),
                ("itemtype", models.CharField(max_length=100)),
                ("rating", models.IntegerField()),
                ("availability", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app1.fooditem"
                    ),
                ),
            ],
        ),
    ]
