# Generated by Django 5.0.7 on 2024-08-17 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="rating",
            field=models.FloatField(),
        ),
    ]
