# Generated by Django 5.0.7 on 2024-08-18 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0003_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="app1.cart"
            ),
        ),
    ]
